---
title: R Getting More From datatables DT
author: Christopher Hopkinson
date: '2017-04-20'
slug: r-getting-more-from-datatables-dt
categories:
  - R
  - Data Visualisation
tags:
  - R
  - datatables
  - DT
  - R Markdown
  - crosstalk
---

# Introduction

The [DT](https://rstudio.github.io/DT/) package is an R package built on top of the javascript library [datatables](https://datatables.net/) by the RStudio team. They can be used in RMarkdown and Shiny to create interactive tables. If you want to learn the basics, there are plenty of tutorials. The DT R package allows us to write R code to generate the HTML widgets. The package manages to surface much of the functionality of the javascript library and, with a little additional javascript, can be extended further. From a data visualisation perspective, this flexibility creates an opportunity. We can weave a striking amount of information into a single table while keeping it neat and readable. 

# What will be covered in this series

The objective is to get to something that looks like this:

```{r}



```


The subjects to cover are:

* Conditional Formatting of text
* Data bars and customised stacked databars
* Sparklines
* Tooltips
* crosstalk - allowing datatables to interact with each other


